# Koyeb FastAPI 배포 설정
[build]
  context = "backend"
  dockerfile = "Dockerfile.python"

[deploy]
  # 애플리케이션 이름
  name = "daily-messages-api"
  
  # 리전 설정
  regions = ["fra"]  # Frankfurt
  
  # 인스턴스 설정
  instance_type = "nano"
  
  # 포트 설정
  ports = [
    { port = 3002, protocol = "http" }
  ]
  
  # 환경 변수
  env = [
    "DB_SCHEMA=morning_prod",
    "PYTHONPATH=/app",
    "PYTHONUNBUFFERED=1",
    "PORT=3002"
  ]
  
  # 헬스체크 설정
  health_check = { path = "/health", port = 3002 }
  
  # 도메인 설정
  routes = [
    { path = "/", methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"] }
  ]