[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://daily-messages-api-production.up.railway.app"
  REACT_APP_ENVIRONMENT = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { REACT_APP_API_BASE_URL = "https://daily-messages-api-production.up.railway.app", REACT_APP_ENVIRONMENT = "production" }